[Date]
date.timezone="UTC"
expose_php= Off

[APCu]
apc.enabled=1
apc.shm_size=32M
apc.ttl=7200
apc.user_ttl=7200
apc.gc_ttl=3600
apc.entries_hint=4096
apc.slam_defense=1
apc.enable_cli=1

[Redis]
redis.arrays.autorehash=1
redis.arrays.connecttimeout=0
redis.arrays.readtimeout=0
redis.arrays.lazyconnect=1
redis.arrays.consistent=1
redis.arrays.distributor="phpredis"
redis.clusters.cache_slots=1
redis.clusters.timeout=0
redis.clusters.read_timeout=0
redis.pconnect.pooling_enabled=1
redis.pconnect.connection_limit=0
redis.session.locking_enabled=0
redis.session.lock_expire=0
redis.session.lock_wait_time=2000